# Numpy

#### 1.Создать вектор (одномерный массив) размера 100, заполненный нулями

In [2]:
import numpy as np

In [6]:
z=np.zeros(100)
print(f'Вектор:\n{z}')

Вектор:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


#### 2.Создать вектор размера 100, заполненный единицами

In [7]:
z=np.ones(100)
print(f'Вектор:\n{z}')

Вектор:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


#### 3.Создать вектор размера 100, заполненный числом 3

In [10]:
z=np.full(100,3)
print(f'Вектор:\n{z}')

Вектор:
[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]


#### 4. Поменять 2 строки в матрице

In [27]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(f'Матрица:\n{a}')

Матрица:
[[1 2 3]
 [4 5 6]]


In [69]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a[[0,1]] = a[[1,0]]
print(a)

[[4 5 6]
 [1 2 3]]


#### 5. Создать вектор со значениями от 10 до 100

In [16]:
z=np.arange(10,100)
print(f'Вектор:\n{z}')

Вектор:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


#### 6. Создать матрицу (двумерный массив) 4x4 со значениями от 0 до 16

In [29]:
a = np.array([[0,1,2,3], [4,5,6,7],[8,9,10,11],[12,13,14,15]])
print(f'Матрица:\n{a}')

Матрица:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


#### 7. Создать 3x3 единичную матрицу

In [36]:
a=np.ones((3,3))
print(f'Матрица:\n{a}')

Матрица:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


#### 8. Создать массив 3x3x3 со случайными значениями

In [37]:
np.random.sample ((3,3,3))

array([[[0.3398233 , 0.78760215, 0.4745331 ],
        [0.91585146, 0.22229825, 0.17261676],
        [0.50630077, 0.79703763, 0.97233041]],

       [[0.21044395, 0.8702025 , 0.52847165],
        [0.18345802, 0.4937892 , 0.91446062],
        [0.71588551, 0.22668174, 0.24064079]],

       [[0.06938907, 0.98076361, 0.23764096],
        [0.16131946, 0.13115523, 0.37115278],
        [0.86172863, 0.76872643, 0.15097081]]])

#### 9. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [39]:
a=np.random.sample ((10,10))
a

array([[0.10245319, 0.82284941, 0.77486917, 0.70258519, 0.19827227,
        0.17268468, 0.15160145, 0.94328901, 0.60155908, 0.27984843],
       [0.85200274, 0.95442818, 0.21838844, 0.48496055, 0.71619863,
        0.08890431, 0.10238273, 0.82600643, 0.83071218, 0.44048204],
       [0.60682995, 0.53816214, 0.79090963, 0.34150925, 0.8108752 ,
        0.94876732, 0.69980718, 0.42819112, 0.13330672, 0.57081856],
       [0.08429713, 0.55003863, 0.78188569, 0.96437691, 0.44350964,
        0.88331129, 0.93982616, 0.70992597, 0.88660232, 0.69672516],
       [0.69933858, 0.09374562, 0.16322257, 0.2511489 , 0.09321683,
        0.72471763, 0.74952273, 0.98510729, 0.28874364, 0.88849638],
       [0.51638071, 0.56535938, 0.08245839, 0.20522293, 0.86103867,
        0.75859149, 0.68372723, 0.35673867, 0.51524196, 0.32528631],
       [0.26446911, 0.5393436 , 0.23624095, 0.08426557, 0.62695868,
        0.45496126, 0.61076701, 0.01376534, 0.45019627, 0.97533899],
       [0.3449785 , 0.31964762, 0.5102433

In [45]:
a=np.random.sample ((10,10))
m=np.min(a)
m

0.009901885454341675

In [46]:
a=np.random.sample ((10,10))
n=np.max(a)
n

0.9956842407315295

#### 10. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [47]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.45684705940591996


#### 11. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [48]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 12. Перемножить матрицы 5x3 и 3x2

In [50]:
Z = np.dot(np.random.sample((5,3)), np.random.sample((3,2)))
print(Z)

[[0.57214845 0.45636173]
 [0.51665381 0.46806368]
 [0.86804948 0.74668524]
 [0.43662882 0.6501458 ]
 [0.66163569 0.73622956]]


#### 13. Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [55]:
Z = np.arange(10)
Z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
Z[(3 < Z) & (Z <= 8)] *= -1
Z

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9])

#### 14. Создать 5x5 матрицу со значениями в строках от 0 до 4

In [57]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 15. Отнять среднее из каждой строки в матрице

In [66]:
X = np.random.rand(2,4)
Y = X - X.mean(axis=1, keepdims=True)
X,Y

(array([[0.5494389 , 0.15935702, 0.79433022, 0.07013765],
        [0.06289193, 0.69529028, 0.98752462, 0.70496427]]),
 array([[ 0.15612295, -0.23395892,  0.40101427, -0.3231783 ],
        [-0.54977585,  0.08262251,  0.37485684,  0.09229649]]))